---
# This is the TorqueBox configuration file. Refer to the TorqueBox
# documentation at http://torquebox.org/documentation/current/
# for all configuration options.
web:
  context: "/"
jobs:
  mail_reminder:
    job: Reminder
    cron: "0 0 * * * ?"
    description: Send daily reminders of items that need refreshing
    singleton: true
